## Getting familiar with numpy arrays

#### 1) Import the numpy module and use a shorter namespace

In [4]:
import numpy as np

#### 2) Create an array containing only 0s with shape (5,5)

In [5]:
array=np.zeros(shape=(5,6))
print(array)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### 3) Get the shape of this array

In [6]:
array.shape

(5, 6)

#### 4) Fill the array with random values, uniformly distributed between -1 and 1, using a loop 

(The point of numpy is however to not do this and write things in a vectorized way directly)

In [7]:
nb_lines = array.shape[0]
nb_columns = array.shape[1]
for line in range(nb_lines):
    for column in range(nb_columns):
        array[line, column] = np.random.uniform(low=-1, high=1)

In [8]:
array

array([[ 0.21224756, -0.27580839,  0.44585531, -0.17201706, -0.14132571,
        -0.89282519],
       [ 0.43224587,  0.6876604 , -0.91721827,  0.47736652,  0.34609439,
         0.43343273],
       [ 0.08215403,  0.17404975, -0.34423611,  0.66849461, -0.84227268,
         0.25334862],
       [-0.08076805, -0.49752097,  0.34919003,  0.5008021 , -0.74224476,
        -0.55124357],
       [-0.8786451 , -0.15530054, -0.5799254 ,  0.85335641, -0.93555884,
         0.47829641]])

#### 5) Rebuild (5,5) random arrays with unifomly distributed values without using a loop

In [9]:
array_1 = np.random.randint(low=-1, high=2, size=(3, 3))
array_2 = np.random.randint(low=-1, high=1, size=(3, 3))
array_3 = np.random.randint(low=-1, high=1, size=(3, 5))

In [41]:
array_1

array([[ 0,  0,  0],
       [-1,  1, -1],
       [-1,  1,  0]])

In [42]:
array_2

array([[ 0,  0, -1],
       [ 0,  0, -1],
       [-1, -1,  0]])

In [43]:
array_3

array([[ 0, -1, -1,  0,  0],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1]])

#### 6) Compute the matrix product and the elementwise product of these arrays

In [12]:
array_1 @ array_3

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  1,  0,  0],
       [-1,  0,  0, -1, -1]])

In [41]:
array_1 * array_2

array([[ 0, -1,  0],
       [ 0,  1,  0],
       [ 0,  0,  1]])

#### 7) Transpose the array

In [18]:
array_3.T

array([[ 0, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1],
       [ 0, -1, -1],
       [ 0, -1, -1]])

#### 7) Check the sign of entries of th array

In [20]:
array_3 >= 0

array([[ True, False, False,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]])

#### 8) Get the indexes where the array is positive

In [21]:
np.where(array_3 >= 0)

(array([0, 0, 0]), array([0, 3, 4]))

In [45]:
array

array([[ 0.57094843,  0.12937255, -0.67920725],
       [ 0.89492646, -0.47048495,  0.48283882],
       [-0.88812305,  0.89135566,  0.11703082],
       [ 0.22566329, -0.14278495, -0.25792282],
       [-0.51674701, -0.46320574, -0.76161228]])

#### 9) Compute the sum of the element in the second line with a loop

In [32]:
result = 0
for column in range(array_3.shape[1]):
    result += array_3[1, column]

In [33]:
result

-5

#### 10) Compute the sum of the elements in the second line without a loop

In [26]:
array_3

array([[ 0, -1, -1,  0,  0],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1]])

In [27]:
array_3[1].sum()

-5

#### 11) Compute the sum of the elements in all lines, using the keword argument "axis" 

In [35]:
array_3.sum(axis=0)

array([-2, -3, -3, -2, -2])

#### 13) Compute the sum of all elements in the array

In [37]:
array_3.sum()

-12

#### 14) Check if all entries are positive

In [38]:
np.all(array >=0)

False

### 15) Compare two writings of the matrix multiplication

In [51]:
np.matmul(array3, array2)

array([[-47,  57, -50],
       [-82, -95, -73]])

In [50]:
array3 @ array2

array([[-47,  57, -50],
       [-82, -95, -73]])